#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the hello_user.mk file instead.
#

# Constants automatically defined by the selected modules
hello_DEBUG = 1

# Our target application
TRG += hello

hello_PREFIX = "arm-none-eabi-"

hello_SUFFIX = ""

hello_SRC_PATH = boards/nucleo-l152re/examples/hello

hello_HW_PATH = boards/nucleo-l152re

# Files automatically generated by the wizard. DO NOT EDIT, USE hello_USER_CSRC INSTEAD!
hello_WIZARD_CSRC = \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE hello_USER_PCSRC INSTEAD!
hello_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE hello_USER_CPPASRC INSTEAD!
hello_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE hello_USER_CXXSRC INSTEAD!
hello_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE hello_USER_ASRC INSTEAD!
hello_WIZARD_ASRC = \
	 \
	#

hello_CPPFLAGS = -D'CPU_FREQ=(32000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(hello_HW_PATH) -I$(hello_SRC_PATH) $(hello_CPU_CPPFLAGS) $(hello_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_LDFLAGS = $(hello_CPU_LDFLAGS) $(hello_WIZARD_LDFLAGS) $(hello_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_CPPAFLAGS = $(hello_CPU_CPPAFLAGS) $(hello_WIZARD_CPPAFLAGS) $(hello_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_CSRC = $(hello_CPU_CSRC) $(hello_WIZARD_CSRC) $(hello_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_PCSRC = $(hello_CPU_PCSRC) $(hello_WIZARD_PCSRC) $(hello_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_CPPASRC = $(hello_CPU_CPPASRC) $(hello_WIZARD_CPPASRC) $(hello_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_CXXSRC = $(hello_CPU_CXXSRC) $(hello_WIZARD_CXXSRC) $(hello_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_ASRC = $(hello_CPU_ASRC) $(hello_WIZARD_ASRC) $(hello_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
hello_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
hello_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
hello_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32L152RE__
hello_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
hello_PROGRAMMER_CPU = stm32
hello_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
hello_CPU = cortex-m3
hello_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
hello_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
hello_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32l152re_rom.ld
hello_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(hello_SRC_PATH)/hello_user.mk
