// Empty main.c file generated by the wizard
#include <cpu/irq.h>

static void init(void)
{
	IRQ_ENABLE;
	// insert initialization calls here
}

int main(void)
{
	init();
	while (1)
	{
		// your code goes here
	}

	return 0;
}

