#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the arduino-mega_kernel_user.mk file instead.
#

# Constants automatically defined by the selected modules
arduino-mega_kernel_DEBUG = 1

# Our target application
TRG += arduino-mega_kernel

arduino-mega_kernel_PREFIX = "avr-"

arduino-mega_kernel_SUFFIX = ""

arduino-mega_kernel_SRC_PATH = boards/arduino-mega/templates/arduino-mega_kernel

arduino-mega_kernel_HW_PATH = boards/arduino-mega

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino-mega_kernel_USER_CSRC INSTEAD!
arduino-mega_kernel_WIZARD_CSRC = \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/kern/signal.c \
	bertos/kern/sem.c \
	bertos/struct/heap.c \
	bertos/io/kfile.c \
	bertos/mware/hex.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/drv/timer.c \
	bertos/mware/event.c \
	bertos/kern/proc.c \
	bertos/mware/formatwr.c \
	bertos/drv/ser.c \
	bertos/kern/monitor.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino-mega_kernel_USER_PCSRC INSTEAD!
arduino-mega_kernel_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino-mega_kernel_USER_CPPASRC INSTEAD!
arduino-mega_kernel_WIZARD_CPPASRC = \
	bertos/cpu/avr/hw/switch_ctx_avr.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino-mega_kernel_USER_CXXSRC INSTEAD!
arduino-mega_kernel_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino-mega_kernel_USER_ASRC INSTEAD!
arduino-mega_kernel_WIZARD_ASRC = \
	 \
	#

arduino-mega_kernel_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(arduino-mega_kernel_HW_PATH) -I$(arduino-mega_kernel_SRC_PATH) $(arduino-mega_kernel_CPU_CPPFLAGS) $(arduino-mega_kernel_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_LDFLAGS = $(arduino-mega_kernel_CPU_LDFLAGS) $(arduino-mega_kernel_WIZARD_LDFLAGS) $(arduino-mega_kernel_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_CPPAFLAGS = $(arduino-mega_kernel_CPU_CPPAFLAGS) $(arduino-mega_kernel_WIZARD_CPPAFLAGS) $(arduino-mega_kernel_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_CSRC = $(arduino-mega_kernel_CPU_CSRC) $(arduino-mega_kernel_WIZARD_CSRC) $(arduino-mega_kernel_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_PCSRC = $(arduino-mega_kernel_CPU_PCSRC) $(arduino-mega_kernel_WIZARD_PCSRC) $(arduino-mega_kernel_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_CPPASRC = $(arduino-mega_kernel_CPU_CPPASRC) $(arduino-mega_kernel_WIZARD_CPPASRC) $(arduino-mega_kernel_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_CXXSRC = $(arduino-mega_kernel_CPU_CXXSRC) $(arduino-mega_kernel_WIZARD_CXXSRC) $(arduino-mega_kernel_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_ASRC = $(arduino-mega_kernel_CPU_ASRC) $(arduino-mega_kernel_WIZARD_ASRC) $(arduino-mega_kernel_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino-mega_kernel_MCU = atmega1280
arduino-mega_kernel_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
arduino-mega_kernel_PROGRAMMER_CPU = atmega1280
arduino-mega_kernel_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
arduino-mega_kernel_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
arduino-mega_kernel_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
arduino-mega_kernel_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(arduino-mega_kernel_SRC_PATH)/arduino-mega_kernel_user.mk
