#
# Copyright 2009 Develer S.r.l. (http://www.develer.com/)
# All rights reserved.
#
# Makefile template for BeRTOS wizard.
#
# Author: Lorenzo Berni <duplo@develer.com>
#
#

# Programmer interface configuration, see http://dev.bertos.org/wiki/ProgrammerInterface for help
avr-kern_PROGRAMMER_TYPE = none
avr-kern_PROGRAMMER_PORT = none

# Files included by the user.
avr-kern_USER_CSRC = \
	examples/avr-kern/main.c \
	bertos/kern/proc_test.c \
	bertos/kern/signal_test.c \
	bertos/mware/sprintf.c \
	#

# Files included by the user.
avr-kern_USER_PCSRC = \
	#

# Files included by the user.
avr-kern_USER_CPPASRC = \
	#

# Files included by the user.
avr-kern_USER_CXXSRC = \
	#

# Files included by the user.
avr-kern_USER_ASRC = \
	#

# Flags included by the user.
avr-kern_USER_LDFLAGS = \
	#

# Flags included by the user.
avr-kern_USER_CPPAFLAGS = \
	#

# Flags included by the user.
avr-kern_USER_CPPFLAGS = \
	-Os -fomit-frame-pointer \
	-fno-strict-aliasing \
	-fwrapv \
	#

# Include the mk file generated by the wizard
include examples/avr-kern/avr-kern_wiz.mk
