// Emtpy main.c file generated by the wizard
#include <cfg/debug.h>
#include <cpu/power.h>
#include <cpu/irq.h>
#include <drv/timer.h>
#include <kern/proc.h>
#include <kern/signal.h>
#include <stdio.h>

static void init(void)
{
	kdbg_init();
	proc_init();
	timer_init();

	IRQ_ENABLE;
}

int main(void)
{
	ssize_t i = 4;

	init();
	for (; i; --i) {
		kprintf("starting in %d\n", i);
		timer_delay(1000);
	}
	kputs("\n");

	proc_testRun();
	signal_testRun();
	while (1)
		cpu_relax();

	return 0;
}

