#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the sd_fat_user.mk file instead.
#

# Constants automatically defined by the selected modules
sd_fat_DEBUG = 1

# Our target application
TRG += sd_fat

sd_fat_PREFIX = "arm-none-eabi-"

sd_fat_SUFFIX = ""

sd_fat_SRC_PATH = boards/at91sam7x-ek/examples/sd_fat

sd_fat_HW_PATH = boards/at91sam7x-ek

# Files automatically generated by the wizard. DO NOT EDIT, USE sd_fat_USER_CSRC INSTEAD!
sd_fat_WIZARD_CSRC = \
	bertos/fs/fatfs/diskio.c \
	bertos/cpu/arm/drv/timer_at91.c \
	bertos/mware/sprintf.c \
	bertos/cpu/arm/drv/adc_at91.c \
	bertos/io/kfile.c \
	bertos/cpu/arm/drv/ser_arm.c \
	bertos/cpu/arm/drv/ser_at91.c \
	bertos/drv/adc.c \
	bertos/drv/timer.c \
	bertos/fs/fatfs/ff.c \
	bertos/drv/ser.c \
	bertos/mware/hex.c \
	bertos/drv/tmp123.c \
	bertos/mware/ini_reader.c \
	bertos/cpu/arm/drv/adc_arm.c \
	bertos/struct/kfile_fifo.c \
	bertos/mware/formatwr.c \
	bertos/drv/sd.c \
	bertos/io/kblock.c \
	bertos/mware/event.c \
	bertos/cpu/arm/drv/sysirq_at91.c \
	bertos/cpu/arm/drv/timer_arm.c \
	bertos/fs/fat.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sd_fat_USER_PCSRC INSTEAD!
sd_fat_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sd_fat_USER_CPPASRC INSTEAD!
sd_fat_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sd_fat_USER_CXXSRC INSTEAD!
sd_fat_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sd_fat_USER_ASRC INSTEAD!
sd_fat_WIZARD_ASRC = \
	 \
	#

sd_fat_CPPFLAGS = -D'CPU_FREQ=(48023000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(sd_fat_HW_PATH) -I$(sd_fat_SRC_PATH) $(sd_fat_CPU_CPPFLAGS) $(sd_fat_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_LDFLAGS = $(sd_fat_CPU_LDFLAGS) $(sd_fat_WIZARD_LDFLAGS) $(sd_fat_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_CPPAFLAGS = $(sd_fat_CPU_CPPAFLAGS) $(sd_fat_WIZARD_CPPAFLAGS) $(sd_fat_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_CSRC = $(sd_fat_CPU_CSRC) $(sd_fat_WIZARD_CSRC) $(sd_fat_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_PCSRC = $(sd_fat_CPU_PCSRC) $(sd_fat_WIZARD_PCSRC) $(sd_fat_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_CPPASRC = $(sd_fat_CPU_CPPASRC) $(sd_fat_WIZARD_CPPASRC) $(sd_fat_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_CXXSRC = $(sd_fat_CPU_CXXSRC) $(sd_fat_WIZARD_CXXSRC) $(sd_fat_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_ASRC = $(sd_fat_CPU_ASRC) $(sd_fat_WIZARD_ASRC) $(sd_fat_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sd_fat_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
sd_fat_CPU_CPPAFLAGS = -g -gdwarf-2
sd_fat_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7X256__
sd_fat_CPU_CSRC = bertos/cpu/arm/hw/init_at91.c
sd_fat_PROGRAMMER_CPU = at91sam7
sd_fat_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
sd_fat_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
sd_fat_CPU = arm7tdmi
sd_fat_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
sd_fat_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
sd_fat_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(sd_fat_SRC_PATH)/sd_fat_user.mk
