#Makefile for BeRTOS test.
#This makefile was generated automatically.

V:= 0
default: all

include bertos/config.mk
include ./examples/test/avrtest.mk
include ./examples/test/armtest.mk
include bertos/rules.mk
