#Makefile for BeRTOS test.
#This makefile was generated automatically.

V:= 0
default: all


include bertos/config.mk

include ./examples/test/avrtest.mk
include ./examples/test/armtest.mk

include ./boards/arduino/examples/arduino_aprs/arduino_aprs.mk
include ./boards/arduino/benchmark/arduino_context_switch/arduino_context_switch.mk
include ./boards/arduino/benchmark/arduino_kernel_footprint/arduino_kernel_footprint.mk
include ./boards/arduino/templates/arduino_kernel/arduino_kernel.mk
include ./boards/arduino/templates/arduino_empty/arduino_empty.mk

include ./boards/arduino-mega/examples/arduino-mega_aprs/arduino-mega_aprs.mk
#include ./boards/arduino-mega/benchmark/arduino-mega_context_switch/arduino-mega_context_switch.mk
include ./boards/arduino-mega/benchmark/arduino-mega_kernel_footprint/arduino-mega_kernel_footprint.mk
#include ./boards/arduino-mega/templates/arduino-mega_kernel/arduino-mega_kernel.mk
#include ./boards/arduino-mega/templates/arduino-mega_empty/arduino-mega_empty.mk

include ./boards/triface/examples/triface/triface.mk
#include ./boards/triface/benchmark/triface_context_switch/triface_context_switch.mk
include ./boards/triface/benchmark/triface_kernel_footprint/triface_kernel_footprint.mk
include ./boards/triface/templates/triface_empty/triface_empty.mk
include ./boards/triface/templates/triface_kernel/triface_kernel.mk

include ./boards/at91sam7s-ek/templates/at91sam7s-ek_empty/at91sam7s-ek_empty.mk
include ./boards/at91sam7s-ek/templates/at91sam7s-ek_kernel/at91sam7s-ek_kernel.mk
include ./boards/at91sam7s-ek/benchmark/at91sam7s-ek_context_switch/at91sam7s-ek_context_switch.mk
include ./boards/at91sam7s-ek/benchmark/at91sam7s-ek_kernel_footprint/at91sam7s-ek_kernel_footprint.mk

include ./boards/sam3x-ek/examples/sam3x-ek_display/sam3x-ek_display.mk
include ./boards/sam3x-ek/examples/sam3x-ek_tcp_server/sam3x-ek_tcp_server.mk

include ./boards/sam3n-ek/examples/sam3n-ek_display/sam3n-ek_display.mk

include ./boards/stm32-p103/examples/usbserial/usbserial.mk
include ./boards/stm32-p103/examples/usbmouse/usbmouse.mk
include ./boards/stm32-p103/examples/usbkeyboard/usbkeyboard.mk
include ./boards/ek-lm3s1968/examples/gps/gps.mk
include ./boards/at91sam7x-ek/examples/sd_fat/sd_fat.mk
include ./boards/at91sam7x-ek/examples/at91sam7x-ek_tcp_server/at91sam7x-ek_tcp_server.mk

include bertos/rules.mk
