/*!
 * \file
 * <!--
 * Copyright 2004, 2005 Develer S.r.l. (http://www.develer.com/)
 * This file is part of DevLib - See README.devlib for information.
 * -->
 *
 * \version $Id$
 *
 * \author Bernardo Innocenti <bernie@develer.com>
 *
 * \brief Define application version strings
 */
#include <verstag.h>

/*
 * "buildrev.h" is auto-generated by the build infrastructure,
 * incrementing VERS_BUILD each time the project is rebuilt.
 */
#include "buildrev.h"

const char vers_tag[] = VERS_TAG;
const char vers_build_str[] = _STRINGIZE(VERS_BUILD);
const char vers_host[] = VERS_HOST;
const int vers_build_nr = VERS_BUILD;

