#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the tcp_server_user.mk file instead.
#

# Constants automatically defined by the selected modules
tcp_server_DEBUG = 1

# Our target application
TRG += tcp_server

tcp_server_PREFIX = "arm-none-eabi-"

tcp_server_SUFFIX = ""

tcp_server_SRC_PATH = boards/at91sam7x-ek/examples/tcp_server

tcp_server_HW_PATH = boards/at91sam7x-ek

# Files automatically generated by the wizard. DO NOT EDIT, USE tcp_server_USER_CSRC INSTEAD!
tcp_server_WIZARD_CSRC = \
	bertos/cpu/arm/drv/timer_arm.c \
	bertos/mware/event.c \
	bertos/kern/sem.c \
	bertos/cpu/arm/drv/sysirq_at91.c \
	bertos/struct/heap.c \
	bertos/io/kfile.c \
	bertos/mware/hex.c \
	bertos/cpu/arm/drv/timer_at91.c \
	bertos/cpu/arm/drv/ser_at91.c \
	bertos/cpu/arm/drv/eth_at91.c \
	bertos/drv/timer.c \
	bertos/kern/signal.c \
	bertos/kern/proc.c \
	bertos/mware/formatwr.c \
	bertos/drv/ser.c \
	bertos/kern/monitor.c \
	bertos/net/lwip.c \
	bertos/cpu/arm/drv/ser_arm.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE tcp_server_USER_PCSRC INSTEAD!
tcp_server_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE tcp_server_USER_CPPASRC INSTEAD!
tcp_server_WIZARD_CPPASRC = \
	bertos/cpu/arm/hw/switch_ctx_arm.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE tcp_server_USER_CXXSRC INSTEAD!
tcp_server_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE tcp_server_USER_ASRC INSTEAD!
tcp_server_WIZARD_ASRC = \
	 \
	#

tcp_server_CPPFLAGS = -D'CPU_FREQ=(48023000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(tcp_server_HW_PATH) -I$(tcp_server_SRC_PATH) $(tcp_server_CPU_CPPFLAGS) $(tcp_server_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_LDFLAGS = $(tcp_server_CPU_LDFLAGS) $(tcp_server_WIZARD_LDFLAGS) $(tcp_server_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_CPPAFLAGS = $(tcp_server_CPU_CPPAFLAGS) $(tcp_server_WIZARD_CPPAFLAGS) $(tcp_server_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_CSRC = $(tcp_server_CPU_CSRC) $(tcp_server_WIZARD_CSRC) $(tcp_server_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_PCSRC = $(tcp_server_CPU_PCSRC) $(tcp_server_WIZARD_PCSRC) $(tcp_server_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_CPPASRC = $(tcp_server_CPU_CPPASRC) $(tcp_server_WIZARD_CPPASRC) $(tcp_server_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_CXXSRC = $(tcp_server_CPU_CXXSRC) $(tcp_server_WIZARD_CXXSRC) $(tcp_server_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_ASRC = $(tcp_server_CPU_ASRC) $(tcp_server_WIZARD_ASRC) $(tcp_server_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
tcp_server_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
tcp_server_CPU_CPPAFLAGS = -g -gdwarf-2
tcp_server_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7X256__
tcp_server_CPU_CSRC = bertos/cpu/arm/hw/init_at91.c
tcp_server_PROGRAMMER_CPU = at91sam7
tcp_server_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
tcp_server_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
tcp_server_CPU = arm7tdmi
tcp_server_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
tcp_server_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
tcp_server_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(tcp_server_SRC_PATH)/tcp_server_user.mk
