#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the triface_empty_user.mk file instead.
#

# Constants automatically defined by the selected modules
triface_empty_DEBUG = 1

# Our target application
TRG += triface_empty

triface_empty_PREFIX = "avr-"

triface_empty_SUFFIX = ""

triface_empty_SRC_PATH = boards/triface/templates/triface_empty

triface_empty_HW_PATH = boards/triface

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_empty_USER_CSRC INSTEAD!
triface_empty_WIZARD_CSRC = \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_empty_USER_PCSRC INSTEAD!
triface_empty_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_empty_USER_CPPASRC INSTEAD!
triface_empty_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_empty_USER_CXXSRC INSTEAD!
triface_empty_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_empty_USER_ASRC INSTEAD!
triface_empty_WIZARD_ASRC = \
	 \
	#

triface_empty_CPPFLAGS = -D'CPU_FREQ=(14745600UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(triface_empty_HW_PATH) -I$(triface_empty_SRC_PATH) $(triface_empty_CPU_CPPFLAGS) $(triface_empty_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_LDFLAGS = $(triface_empty_CPU_LDFLAGS) $(triface_empty_WIZARD_LDFLAGS) $(triface_empty_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_CPPAFLAGS = $(triface_empty_CPU_CPPAFLAGS) $(triface_empty_WIZARD_CPPAFLAGS) $(triface_empty_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_CSRC = $(triface_empty_CPU_CSRC) $(triface_empty_WIZARD_CSRC) $(triface_empty_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_PCSRC = $(triface_empty_CPU_PCSRC) $(triface_empty_WIZARD_PCSRC) $(triface_empty_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_CPPASRC = $(triface_empty_CPU_CPPASRC) $(triface_empty_WIZARD_CPPASRC) $(triface_empty_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_CXXSRC = $(triface_empty_CPU_CXXSRC) $(triface_empty_WIZARD_CXXSRC) $(triface_empty_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_ASRC = $(triface_empty_CPU_ASRC) $(triface_empty_WIZARD_ASRC) $(triface_empty_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_empty_MCU = atmega1281
triface_empty_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
triface_empty_PROGRAMMER_CPU = atmega1281
triface_empty_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
triface_empty_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
triface_empty_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
triface_empty_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(triface_empty_SRC_PATH)/triface_empty_user.mk
