#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the armtest_user.mk file instead.
#

# Constants automatically defined by the selected modules
armtest_DEBUG = 1

# Our target application
TRG += armtest

armtest_PREFIX = "arm-none-eabi-"

armtest_SUFFIX = ""

armtest_SRC_PATH = examples/test

armtest_HW_PATH = bertos/hw

# Files automatically generated by the wizard. DO NOT EDIT, USE armtest_USER_CSRC INSTEAD!
armtest_WIZARD_CSRC = \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE armtest_USER_PCSRC INSTEAD!
armtest_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE armtest_USER_CPPASRC INSTEAD!
armtest_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE armtest_USER_CXXSRC INSTEAD!
armtest_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE armtest_USER_ASRC INSTEAD!
armtest_WIZARD_ASRC = \
	 \
	#

armtest_CPPFLAGS = -D'CPU_FREQ=(48054857UL)' -D'ARCH=(ARCH_NIGHTTEST)' -D'WIZ_AUTOGEN' -I$(armtest_HW_PATH) -I$(armtest_SRC_PATH) $(armtest_CPU_CPPFLAGS) $(armtest_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_LDFLAGS = $(armtest_CPU_LDFLAGS) $(armtest_WIZARD_LDFLAGS) $(armtest_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_CPPAFLAGS = $(armtest_CPU_CPPAFLAGS) $(armtest_WIZARD_CPPAFLAGS) $(armtest_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_CSRC = $(armtest_CPU_CSRC) $(armtest_WIZARD_CSRC) $(armtest_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_PCSRC = $(armtest_CPU_PCSRC) $(armtest_WIZARD_PCSRC) $(armtest_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_CPPASRC = $(armtest_CPU_CPPASRC) $(armtest_WIZARD_CPPASRC) $(armtest_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_CXXSRC = $(armtest_CPU_CXXSRC) $(armtest_WIZARD_CXXSRC) $(armtest_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_ASRC = $(armtest_CPU_ASRC) $(armtest_WIZARD_ASRC) $(armtest_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
armtest_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
armtest_CPU_CPPAFLAGS = -g -gdwarf-2
armtest_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7X256__
armtest_CPU_CSRC =
armtest_PROGRAMMER_CPU = at91sam7
armtest_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
armtest_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
armtest_CPU = arm7tdmi
armtest_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
armtest_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
armtest_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(armtest_SRC_PATH)/armtest_user.mk
