#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the usbmouse_user.mk file instead.
#

# Constants automatically defined by the selected modules
usbmouse_DEBUG = 1

# Our target application
TRG += usbmouse

usbmouse_PREFIX = "arm-none-eabi-"

usbmouse_SUFFIX = ""

usbmouse_SRC_PATH = boards/stm32-p103/examples/usbmouse

usbmouse_HW_PATH = boards/stm32-p103

# Files automatically generated by the wizard. DO NOT EDIT, USE usbmouse_USER_CSRC INSTEAD!
usbmouse_WIZARD_CSRC = \
	bertos/struct/heap.c \
	bertos/drv/usbmouse.c \
	bertos/mware/event.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/drv/kbd.c \
	bertos/io/kfile.c \
	bertos/mware/formatwr.c \
	bertos/cpu/cortex-m3/drv/usb_stm32.c \
	bertos/drv/timer.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbmouse_USER_PCSRC INSTEAD!
usbmouse_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbmouse_USER_CPPASRC INSTEAD!
usbmouse_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbmouse_USER_CXXSRC INSTEAD!
usbmouse_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbmouse_USER_ASRC INSTEAD!
usbmouse_WIZARD_ASRC = \
	 \
	#

usbmouse_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(usbmouse_HW_PATH) -I$(usbmouse_SRC_PATH) $(usbmouse_CPU_CPPFLAGS) $(usbmouse_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_LDFLAGS = $(usbmouse_CPU_LDFLAGS) $(usbmouse_WIZARD_LDFLAGS) $(usbmouse_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_CPPAFLAGS = $(usbmouse_CPU_CPPAFLAGS) $(usbmouse_WIZARD_CPPAFLAGS) $(usbmouse_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_CSRC = $(usbmouse_CPU_CSRC) $(usbmouse_WIZARD_CSRC) $(usbmouse_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_PCSRC = $(usbmouse_CPU_PCSRC) $(usbmouse_WIZARD_PCSRC) $(usbmouse_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_CPPASRC = $(usbmouse_CPU_CPPASRC) $(usbmouse_WIZARD_CPPASRC) $(usbmouse_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_CXXSRC = $(usbmouse_CPU_CXXSRC) $(usbmouse_WIZARD_CXXSRC) $(usbmouse_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_ASRC = $(usbmouse_CPU_ASRC) $(usbmouse_WIZARD_ASRC) $(usbmouse_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbmouse_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
usbmouse_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
usbmouse_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
usbmouse_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
usbmouse_PROGRAMMER_CPU = stm32
usbmouse_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
usbmouse_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
usbmouse_CPU = cortex-m3
usbmouse_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
usbmouse_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
usbmouse_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(usbmouse_SRC_PATH)/usbmouse_user.mk
