#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the arduino_kernel_user.mk file instead.
#

# Constants automatically defined by the selected modules
arduino_kernel_DEBUG = 1

# Our target application
TRG += arduino_kernel

arduino_kernel_PREFIX = "avr-"

arduino_kernel_SUFFIX = ""

arduino_kernel_SRC_PATH = boards/arduino/templates/arduino_kernel

arduino_kernel_HW_PATH = boards/arduino

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kernel_USER_CSRC INSTEAD!
arduino_kernel_WIZARD_CSRC = \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/kern/monitor.c \
	bertos/kern/proc.c \
	bertos/kern/sem.c \
	bertos/kern/signal.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kernel_USER_PCSRC INSTEAD!
arduino_kernel_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kernel_USER_CPPASRC INSTEAD!
arduino_kernel_WIZARD_CPPASRC = \
	bertos/cpu/avr/hw/switch_ctx_avr.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kernel_USER_CXXSRC INSTEAD!
arduino_kernel_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kernel_USER_ASRC INSTEAD!
arduino_kernel_WIZARD_ASRC = \
	 \
	#

arduino_kernel_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(arduino_kernel_HW_PATH) -I$(arduino_kernel_SRC_PATH) $(arduino_kernel_CPU_CPPFLAGS) $(arduino_kernel_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_LDFLAGS = $(arduino_kernel_CPU_LDFLAGS) $(arduino_kernel_WIZARD_LDFLAGS) $(arduino_kernel_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_CPPAFLAGS = $(arduino_kernel_CPU_CPPAFLAGS) $(arduino_kernel_WIZARD_CPPAFLAGS) $(arduino_kernel_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_CSRC = $(arduino_kernel_CPU_CSRC) $(arduino_kernel_WIZARD_CSRC) $(arduino_kernel_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_PCSRC = $(arduino_kernel_CPU_PCSRC) $(arduino_kernel_WIZARD_PCSRC) $(arduino_kernel_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_CPPASRC = $(arduino_kernel_CPU_CPPASRC) $(arduino_kernel_WIZARD_CPPASRC) $(arduino_kernel_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_CXXSRC = $(arduino_kernel_CPU_CXXSRC) $(arduino_kernel_WIZARD_CXXSRC) $(arduino_kernel_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_ASRC = $(arduino_kernel_CPU_ASRC) $(arduino_kernel_WIZARD_ASRC) $(arduino_kernel_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kernel_MCU = atmega328p
arduino_kernel_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
arduino_kernel_PROGRAMMER_CPU = atmega328p
arduino_kernel_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
arduino_kernel_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
arduino_kernel_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
arduino_kernel_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(arduino_kernel_SRC_PATH)/arduino_kernel_user.mk
