#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the triface_user.mk file instead.
#

# Constants automatically defined by the selected modules
triface_DEBUG = 1

# Our target application
TRG += triface

triface_PREFIX = "avr-"

triface_SUFFIX = ""

triface_SRC_PATH = boards/triface/examples/triface

triface_HW_PATH = boards/triface

ifeq ($(CPU), atmega1281)
	triface_hfuse = 0x98
	triface_lfuse = 0x3d
	triface_efuse = 0x7f
	triface_lock = 0x2f
else
	triface_hfuse = 0x88
	triface_lfuse = 0xff
	triface_efuse = 0xff
	triface_lock = 0x2f
endif

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_USER_CSRC INSTEAD!
triface_WIZARD_CSRC = \
	bertos/cpu/avr/drv/adc_avr.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/adc.c \
	bertos/drv/buzzer.c \
	bertos/drv/ser.c \
	bertos/drv/sipo.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/mware/parser.c \
	bertos/mware/readline.c \
	bertos/mware/sprintf.c \
	bertos/net/keytag.c \
	bertos/struct/hashtable.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_USER_PCSRC INSTEAD!
triface_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	bertos/mware/sprintf.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_USER_CPPASRC INSTEAD!
triface_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_USER_CXXSRC INSTEAD!
triface_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE triface_USER_ASRC INSTEAD!
triface_WIZARD_ASRC = \
	 \
	#

triface_CPPFLAGS = -D'CPU_FREQ=(14745600UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(triface_HW_PATH) -I$(triface_SRC_PATH) $(triface_CPU_CPPFLAGS) $(triface_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_LDFLAGS = $(triface_CPU_LDFLAGS) $(triface_WIZARD_LDFLAGS) $(triface_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_CPPAFLAGS = $(triface_CPU_CPPAFLAGS) $(triface_WIZARD_CPPAFLAGS) $(triface_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_CSRC = $(triface_CPU_CSRC) $(triface_WIZARD_CSRC) $(triface_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_PCSRC = $(triface_CPU_PCSRC) $(triface_WIZARD_PCSRC) $(triface_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_CPPASRC = $(triface_CPU_CPPASRC) $(triface_WIZARD_CPPASRC) $(triface_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_CXXSRC = $(triface_CPU_CXXSRC) $(triface_WIZARD_CXXSRC) $(triface_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_ASRC = $(triface_CPU_ASRC) $(triface_WIZARD_ASRC) $(triface_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
triface_MCU = atmega1281
triface_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
triface_PROGRAMMER_CPU = atmega1281
triface_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
triface_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
triface_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
triface_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(triface_SRC_PATH)/triface_user.mk
