#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the usbkeyboard_user.mk file instead.
#

# Constants automatically defined by the selected modules
usbkeyboard_DEBUG = 1

# Our target application
TRG += usbkeyboard

usbkeyboard_PREFIX = "arm-none-eabi-"

usbkeyboard_SUFFIX = ""

usbkeyboard_SRC_PATH = boards/stm32-p103/examples/usbkeyboard

usbkeyboard_HW_PATH = boards/stm32-p103

# Files automatically generated by the wizard. DO NOT EDIT, USE usbkeyboard_USER_CSRC INSTEAD!
usbkeyboard_WIZARD_CSRC = \
	bertos/struct/heap.c \
	bertos/mware/event.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/drv/kbd.c \
	bertos/io/kfile.c \
	bertos/mware/formatwr.c \
	bertos/drv/usbkbd.c \
	bertos/cpu/cortex-m3/drv/usb_stm32.c \
	bertos/drv/timer.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbkeyboard_USER_PCSRC INSTEAD!
usbkeyboard_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbkeyboard_USER_CPPASRC INSTEAD!
usbkeyboard_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbkeyboard_USER_CXXSRC INSTEAD!
usbkeyboard_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE usbkeyboard_USER_ASRC INSTEAD!
usbkeyboard_WIZARD_ASRC = \
	 \
	#

usbkeyboard_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(usbkeyboard_HW_PATH) -I$(usbkeyboard_SRC_PATH) $(usbkeyboard_CPU_CPPFLAGS) $(usbkeyboard_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_LDFLAGS = $(usbkeyboard_CPU_LDFLAGS) $(usbkeyboard_WIZARD_LDFLAGS) $(usbkeyboard_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_CPPAFLAGS = $(usbkeyboard_CPU_CPPAFLAGS) $(usbkeyboard_WIZARD_CPPAFLAGS) $(usbkeyboard_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_CSRC = $(usbkeyboard_CPU_CSRC) $(usbkeyboard_WIZARD_CSRC) $(usbkeyboard_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_PCSRC = $(usbkeyboard_CPU_PCSRC) $(usbkeyboard_WIZARD_PCSRC) $(usbkeyboard_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_CPPASRC = $(usbkeyboard_CPU_CPPASRC) $(usbkeyboard_WIZARD_CPPASRC) $(usbkeyboard_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_CXXSRC = $(usbkeyboard_CPU_CXXSRC) $(usbkeyboard_WIZARD_CXXSRC) $(usbkeyboard_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_ASRC = $(usbkeyboard_CPU_ASRC) $(usbkeyboard_WIZARD_ASRC) $(usbkeyboard_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
usbkeyboard_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
usbkeyboard_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
usbkeyboard_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
usbkeyboard_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
usbkeyboard_PROGRAMMER_CPU = stm32
usbkeyboard_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
usbkeyboard_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
usbkeyboard_CPU = cortex-m3
usbkeyboard_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
usbkeyboard_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
usbkeyboard_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(usbkeyboard_SRC_PATH)/usbkeyboard_user.mk
