#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the aprs_user.mk file instead.
#

# Constants automatically defined by the selected modules
aprs_DEBUG = 1

# Our target application
TRG += aprs

aprs_PREFIX = "avr-"

aprs_SUFFIX = ""

aprs_SRC_PATH = boards/arduino/examples/aprs

aprs_HW_PATH = boards/arduino

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_USER_CSRC INSTEAD!
aprs_WIZARD_CSRC = \
	aprs/hw/hw_afsk.c \
	bertos/kern/kfile.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/net/afsk.c \
	bertos/net/ax25.c \
	bertos/mware/formatwr.c \
	bertos/algo/crc_ccitt.c \
	bertos/drv/timer.c \
	bertos/mware/event.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/drv/ser.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_USER_PCSRC INSTEAD!
aprs_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_USER_CPPASRC INSTEAD!
aprs_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_USER_CXXSRC INSTEAD!
aprs_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_USER_ASRC INSTEAD!
aprs_WIZARD_ASRC = \
	 \
	#

aprs_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(aprs_HW_PATH) -I$(aprs_SRC_PATH) $(aprs_CPU_CPPFLAGS) $(aprs_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_LDFLAGS = $(aprs_CPU_LDFLAGS) $(aprs_WIZARD_LDFLAGS) $(aprs_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_CPPAFLAGS = $(aprs_CPU_CPPAFLAGS) $(aprs_WIZARD_CPPAFLAGS) $(aprs_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_CSRC = $(aprs_CPU_CSRC) $(aprs_WIZARD_CSRC) $(aprs_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_PCSRC = $(aprs_CPU_PCSRC) $(aprs_WIZARD_PCSRC) $(aprs_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_CPPASRC = $(aprs_CPU_CPPASRC) $(aprs_WIZARD_CPPASRC) $(aprs_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_CXXSRC = $(aprs_CPU_CXXSRC) $(aprs_WIZARD_CXXSRC) $(aprs_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_ASRC = $(aprs_CPU_ASRC) $(aprs_WIZARD_ASRC) $(aprs_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
aprs_PROGRAMMER_CPU = atmega328p
aprs_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
aprs_MCU = atmega328p
aprs_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh
aprs_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
aprs_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/

include $(aprs_SRC_PATH)/aprs_user.mk
