#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the empty_user.mk file instead.
#

# Constants automatically defined by the selected modules
empty_DEBUG = 1

# Our target application
TRG += empty

empty_PREFIX = "avr-"

empty_SUFFIX = ""

empty_SRC_PATH = boards/triface/templates/empty

empty_HW_PATH = boards/triface

# Files automatically generated by the wizard. DO NOT EDIT, USE empty_USER_CSRC INSTEAD!
empty_WIZARD_CSRC = \
	bertos/kern/kfile.c \
	bertos/kern/signal.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/kern/sem.c \
	bertos/struct/heap.c \
	bertos/mware/formatwr.c \
	bertos/drv/timer.c \
	bertos/mware/event.c \
	bertos/kern/proc.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/drv/ser.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE empty_USER_PCSRC INSTEAD!
empty_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE empty_USER_CPPASRC INSTEAD!
empty_WIZARD_CPPASRC = \
	bertos/cpu/avr/hw/switch_ctx_avr.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE empty_USER_CXXSRC INSTEAD!
empty_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE empty_USER_ASRC INSTEAD!
empty_WIZARD_ASRC = \
	 \
	#

empty_CPPFLAGS = -D'CPU_FREQ=(14745600UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(empty_HW_PATH) -I$(empty_SRC_PATH) $(empty_CPU_CPPFLAGS) $(empty_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_LDFLAGS = $(empty_CPU_LDFLAGS) $(empty_WIZARD_LDFLAGS) $(empty_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_CPPAFLAGS = $(empty_CPU_CPPAFLAGS) $(empty_WIZARD_CPPAFLAGS) $(empty_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_CSRC = $(empty_CPU_CSRC) $(empty_WIZARD_CSRC) $(empty_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_PCSRC = $(empty_CPU_PCSRC) $(empty_WIZARD_PCSRC) $(empty_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_CPPASRC = $(empty_CPU_CPPASRC) $(empty_WIZARD_CPPASRC) $(empty_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_CXXSRC = $(empty_CPU_CXXSRC) $(empty_WIZARD_CXXSRC) $(empty_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_ASRC = $(empty_CPU_ASRC) $(empty_WIZARD_ASRC) $(empty_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
empty_MCU = atmega1281
empty_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
empty_PROGRAMMER_CPU = atmega1281
empty_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
empty_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
empty_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
empty_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(empty_SRC_PATH)/empty_user.mk
