#
# Copyright 2009 Develer S.r.l. (http://www.develer.com/)
# All rights reserved.
#
# Makefile template for BeRTOS wizard.
#
# Author: Lorenzo Berni <duplo@develer.com>
#
#

# Constants automatically defined by the selected modules
lpc2378_DEBUG = 1

# Our target application
TRG += lpc2378

lpc2378_PREFIX = "arm-none-eabi-"

lpc2378_SUFFIX = ""

# Files automatically generated by the wizard. DO NOT EDIT, USE lpc2378_USER_CSRC INSTEAD!
lpc2378_WIZARD_CSRC = \
	bertos/mware/hex.c \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE lpc2378_USER_PCSRC INSTEAD!
lpc2378_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE lpc2378_USER_CPPASRC INSTEAD!
lpc2378_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE lpc2378_USER_CXXSRC INSTEAD!
lpc2378_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE lpc2378_USER_ASRC INSTEAD!
lpc2378_WIZARD_ASRC = \
	 \
	#

lpc2378_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -Iexamples/lpc2378/ $(lpc2378_CPU_CPPFLAGS) $(lpc2378_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_LDFLAGS = $(lpc2378_CPU_LDFLAGS) $(lpc2378_WIZARD_LDFLAGS) $(lpc2378_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_CPPAFLAGS = $(lpc2378_CPU_CPPAFLAGS) $(lpc2378_WIZARD_CPPAFLAGS) $(lpc2378_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_CSRC = $(lpc2378_CPU_CSRC) $(lpc2378_WIZARD_CSRC) $(lpc2378_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_PCSRC = $(lpc2378_CPU_PCSRC) $(lpc2378_WIZARD_PCSRC) $(lpc2378_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_CPPASRC = $(lpc2378_CPU_CPPASRC) $(lpc2378_WIZARD_CPPASRC) $(lpc2378_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_CXXSRC = $(lpc2378_CPU_CXXSRC) $(lpc2378_WIZARD_CXXSRC) $(lpc2378_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_ASRC = $(lpc2378_CPU_ASRC) $(lpc2378_WIZARD_ASRC) $(lpc2378_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
lpc2378_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_lpc2.S
lpc2378_CPU_CPPAFLAGS = -g -gdwarf-2
lpc2378_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_LPC2378__
lpc2378_CPU_CSRC = bertos/cpu/arm/hw/init_lpc2.c
lpc2378_PROGRAMMER_CPU = lpc2378
lpc2378_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
lpc2378_CPU = arm7tdmi
lpc2378_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
lpc2378_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
lpc2378_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/lpc2378.ld
lpc2378_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh
