#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the at91sam7s-ek_kernel_user.mk file instead.
#

# Constants automatically defined by the selected modules
at91sam7s-ek_kernel_DEBUG = 1

# Our target application
TRG += at91sam7s-ek_kernel

at91sam7s-ek_kernel_PREFIX = "arm-none-eabi-"

at91sam7s-ek_kernel_SUFFIX = ""

at91sam7s-ek_kernel_SRC_PATH = boards/at91sam7s-ek/templates/at91sam7s-ek_kernel

at91sam7s-ek_kernel_HW_PATH = boards/at91sam7s-ek

# Files automatically generated by the wizard. DO NOT EDIT, USE at91sam7s-ek_kernel_USER_CSRC INSTEAD!
at91sam7s-ek_kernel_WIZARD_CSRC = \
	bertos/cpu/arm/drv/timer_arm.c \
	bertos/mware/event.c \
	bertos/kern/sem.c \
	bertos/cpu/arm/drv/sysirq_at91.c \
	bertos/struct/heap.c \
	bertos/io/kfile.c \
	bertos/mware/hex.c \
	bertos/cpu/arm/drv/timer_at91.c \
	bertos/cpu/arm/drv/ser_at91.c \
	bertos/drv/timer.c \
	bertos/kern/signal.c \
	bertos/kern/proc.c \
	bertos/mware/formatwr.c \
	bertos/drv/ser.c \
	bertos/kern/monitor.c \
	bertos/cpu/arm/drv/ser_arm.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE at91sam7s-ek_kernel_USER_PCSRC INSTEAD!
at91sam7s-ek_kernel_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE at91sam7s-ek_kernel_USER_CPPASRC INSTEAD!
at91sam7s-ek_kernel_WIZARD_CPPASRC = \
	bertos/cpu/arm/hw/switch_ctx_arm.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE at91sam7s-ek_kernel_USER_CXXSRC INSTEAD!
at91sam7s-ek_kernel_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE at91sam7s-ek_kernel_USER_ASRC INSTEAD!
at91sam7s-ek_kernel_WIZARD_ASRC = \
	 \
	#

at91sam7s-ek_kernel_CPPFLAGS = -D'CPU_FREQ=(48054857UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(at91sam7s-ek_kernel_HW_PATH) -I$(at91sam7s-ek_kernel_SRC_PATH) $(at91sam7s-ek_kernel_CPU_CPPFLAGS) $(at91sam7s-ek_kernel_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_LDFLAGS = $(at91sam7s-ek_kernel_CPU_LDFLAGS) $(at91sam7s-ek_kernel_WIZARD_LDFLAGS) $(at91sam7s-ek_kernel_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_CPPAFLAGS = $(at91sam7s-ek_kernel_CPU_CPPAFLAGS) $(at91sam7s-ek_kernel_WIZARD_CPPAFLAGS) $(at91sam7s-ek_kernel_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_CSRC = $(at91sam7s-ek_kernel_CPU_CSRC) $(at91sam7s-ek_kernel_WIZARD_CSRC) $(at91sam7s-ek_kernel_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_PCSRC = $(at91sam7s-ek_kernel_CPU_PCSRC) $(at91sam7s-ek_kernel_WIZARD_PCSRC) $(at91sam7s-ek_kernel_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_CPPASRC = $(at91sam7s-ek_kernel_CPU_CPPASRC) $(at91sam7s-ek_kernel_WIZARD_CPPASRC) $(at91sam7s-ek_kernel_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_CXXSRC = $(at91sam7s-ek_kernel_CPU_CXXSRC) $(at91sam7s-ek_kernel_WIZARD_CXXSRC) $(at91sam7s-ek_kernel_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_ASRC = $(at91sam7s-ek_kernel_CPU_ASRC) $(at91sam7s-ek_kernel_WIZARD_ASRC) $(at91sam7s-ek_kernel_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
at91sam7s-ek_kernel_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
at91sam7s-ek_kernel_CPU_CPPAFLAGS = -g -gdwarf-2
at91sam7s-ek_kernel_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7S256__
at91sam7s-ek_kernel_CPU_CSRC = bertos/cpu/arm/hw/init_at91.c
at91sam7s-ek_kernel_PROGRAMMER_CPU = at91sam7
at91sam7s-ek_kernel_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
at91sam7s-ek_kernel_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
at91sam7s-ek_kernel_CPU = arm7tdmi
at91sam7s-ek_kernel_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
at91sam7s-ek_kernel_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
at91sam7s-ek_kernel_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(at91sam7s-ek_kernel_SRC_PATH)/at91sam7s-ek_kernel_user.mk
