#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the arduino_aprs_user.mk file instead.
#

# Constants automatically defined by the selected modules
arduino_aprs_DEBUG = 1

# Our target application
TRG += arduino_aprs

arduino_aprs_PREFIX = "avr-"

arduino_aprs_SUFFIX = ""

arduino_aprs_SRC_PATH = boards/arduino/examples/arduino_aprs

arduino_aprs_HW_PATH = boards/arduino

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_aprs_USER_CSRC INSTEAD!
arduino_aprs_WIZARD_CSRC = \
	bertos/algo/crc_ccitt.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/net/afsk.c \
	bertos/net/ax25.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_aprs_USER_PCSRC INSTEAD!
arduino_aprs_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_aprs_USER_CPPASRC INSTEAD!
arduino_aprs_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_aprs_USER_CXXSRC INSTEAD!
arduino_aprs_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_aprs_USER_ASRC INSTEAD!
arduino_aprs_WIZARD_ASRC = \
	 \
	#

arduino_aprs_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(arduino_aprs_HW_PATH) -I$(arduino_aprs_SRC_PATH) $(arduino_aprs_CPU_CPPFLAGS) $(arduino_aprs_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_LDFLAGS = $(arduino_aprs_CPU_LDFLAGS) $(arduino_aprs_WIZARD_LDFLAGS) $(arduino_aprs_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_CPPAFLAGS = $(arduino_aprs_CPU_CPPAFLAGS) $(arduino_aprs_WIZARD_CPPAFLAGS) $(arduino_aprs_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_CSRC = $(arduino_aprs_CPU_CSRC) $(arduino_aprs_WIZARD_CSRC) $(arduino_aprs_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_PCSRC = $(arduino_aprs_CPU_PCSRC) $(arduino_aprs_WIZARD_PCSRC) $(arduino_aprs_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_CPPASRC = $(arduino_aprs_CPU_CPPASRC) $(arduino_aprs_WIZARD_CPPASRC) $(arduino_aprs_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_CXXSRC = $(arduino_aprs_CPU_CXXSRC) $(arduino_aprs_WIZARD_CXXSRC) $(arduino_aprs_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_ASRC = $(arduino_aprs_CPU_ASRC) $(arduino_aprs_WIZARD_ASRC) $(arduino_aprs_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_aprs_MCU = atmega328p
arduino_aprs_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
arduino_aprs_PROGRAMMER_CPU = atmega328p
arduino_aprs_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
arduino_aprs_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
arduino_aprs_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
arduino_aprs_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(arduino_aprs_SRC_PATH)/arduino_aprs_user.mk
