#
# Copyright 2009 Develer S.r.l. (http://www.develer.com/)
# All rights reserved.
#
# Makefile template for BeRTOS wizard.
#
# Author: Lorenzo Berni <duplo@develer.com>
#
#

# Include the mk file generated by the wizard
include $pname/$pname_wiz.mk

# Files included by the user.
$pname_USER_CSRC = \
	$main \
	#

# Files included by the user.
$pname_USER_PCSRC = \
	#

# Files included by the user.
$pname_USER_CPPASRC = \
	#

# Files included by the user.
$pname_USER_CXXSRC = \
	#

# Files included by the user.
$pname_USER_ASRC = \
	#

# Programmer interface configuration, see http://dev.bertos.org/wiki/ProgrammerInterface for help
$pname_PROGRAMMER_TYPE = none
$pname_PROGRAMMER_PORT = none


$cpuparameters
